---
name: nfs-server
director_uuid: 8b5a911d-96e7-40dc-a259-a552390f6e7f

stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3263.12'

instance_groups: 
- name: nfsserver
  azs: [env1]
  instances: 1
  networks: 
    - name: VMNetwork
      static_ips: 10.193.96.74
  stemcell: default
  vm_type: small
  persistent_disk_type: '30720'
  jobs:
    - name: nfstestserver
      release: nfs-volume
  properties: {}

releases:
  - name: nfs-volume
    version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
