---
name: nfs-server
director_uuid: b3efa10a-a3ae-4d3d-99b1-3aaf0bcfdf59

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 'latest'

instance_groups:
- name: nfsserver
  azs: [RP01]
  instances: 1
  networks:
    - name: vmnetwork
      static_ips: 10.193.53.248
  stemcell: default
  vm_type: small
  persistent_disk_type: '30720'
  jobs:
    - name: nfstestserver
      release: nfs-volume
  properties: {}

releases:
  - name: nfs-volume
    version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
